### ISSUE TITLE
Google Calendar - Cannot read properties of null (reading 'installed']

### ISSUE THREAD

**Issue by quantumsheep** [quantumsheep/myges-cli#13]
@Nouuu I received this email:
> [...]
> Actuellement, je rencontre un problème dessus, il est impossible de connecter google calendar, il y a un échec de synchronisation à chaque tentative, l’erreur : Cannot read properties of null (reading 'installed’) (photo ci-joint)
> [...]

![Logs](https://user-images.githubusercontent.com/7271496/150119878-1d407656-5682-4b0f-9eac-9a2f1fc20305.png)

**Comment by Nouuu** [comment]
Look like there were a mistake during google authorization token retrieving.

Add more controls on these field to warn before throwing error
