### ISSUE TITLE
api is slow

### ISSUE THREAD

**Issue by alexdieudonne** [quantumsheep/myges-cli#16]
I love your npm plugin a lot, and use it. But i have a problem with the api, the request of get calendar only show the passed event, not the full week as asked.
Can you do something about it? Thanks

**Comment by quantumsheep** [comment]
Hi, sorry to hear that :/ I don't have the issue on my side, can you show me which command or function are you using and what are the results ?

**Comment by alexdieudonne** [comment]
hey sorry, i think i've solved the problem with date's manipulation. Sorry for this. And again thank you for your repo it helps very much esgi's students.
