### ISSUE TITLE
env: can't execute 'node --no-warnings': No such file or directory

### ISSUE THREAD

**Issue by aminnairi** [quantumsheep/myges-cli#5]
## Issue

It does not work when invoked with `npx`.

## Reproduction Steps

```console
$ docker run -itu node -w /home/node node:15.0.0-alpine sh
$ npx myges --version
env: can't execute 'node --no-warnings': No such file or directory
```

**Comment by quantumsheep** [comment]
Seems like not every implementation of `env` handles separated arguments (at least Alpine's one don't).

Removing `--no-warnings` makes it work.

In order to prevent such cases in the future, runtime-testing pipelines will be setup.

**Comment by quantumsheep** [comment]
https://github.com/quantumsheep/myges-cli/commit/715f2277353584322b9fecbf89de393d6fef7e41 fixes the issue.
https://github.com/quantumsheep/myges-cli/actions/runs/867188189 prevents further similar issues.
