### ISSUE TITLE
Unecessary files in package

### ISSUE THREAD

**Issue by aminnairi** [quantumsheep/myges-cli#6]
## Issue

Some files are not ignored when packed before being pushed to NPM packages registry.

GitHub Action workflow files and sources should not be packed and take an unecessary amount of space in the tarball and when downloaded in the client's filesystem.

## Reproduction steps

```console
$ npm pack --dry-run
```

## Additional Context

Adding the following line in the `package.json` file reduce the tarball size from 17.4Kb down to 9.9Kb.

```json
{
  "files": ["dist"]
}
```

Also consider adding an optimization step with `rollup` and `rollup-plugin-terser` for instance to remove unecessary blank spaces in the transpiled files to save theoretically more than 50% added space in the packed tarball.

**Comment by quantumsheep** [comment]
Thanks you for telling me about `rollup`! Package started at 17.8kB, ended up at 6.4kB in https://github.com/quantumsheep/myges-cli/commit/7fdadb6103a3a28797c87d80ec9fbbba277c8b61.
